name: livechatt
description: A livechat package for embedding mobile chat window in your mobile application.
version: 1.5.1
homepage: https://github.com/Mastersam07/livechat
repository: https://github.com/Mastersam07/livechat
issue_tracker: https://github.com/Mastersam07/livechat/issues
documentation: https://github.com/Mastersam07/livechat

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: tech.mastersam.livechat
        pluginClass: LivechatPlugin
      ios:
        pluginClass: LivechatPlugin